collections:
    seasons:
        output: true

defaults:
    - scope:
        path: ""
        type: "seasons"
      values:
        layout: "season"
    - scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
    - scope:
        path: ""
      values:
        layout: "default"

theme: jekyll-theme-midnight
title: Searon's Rankings
description: NCAA DI FBS Rankings
